apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - secrets.yaml
  - volumes.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - nodered-secrets.yaml
  - nodered-volume.yaml
  - nodered-config.yaml
  - nodered-deployment.yaml
