apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nodered-secrets
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: nodered-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: admin-username
      remoteRef:
        key: NODERED_ADMIN_USERNAME
    - secretKey: admin-password-hash
      remoteRef:
        key: NODERED_ADMIN_PASSWORD_HASH
    - secretKey: credential-secret
      remoteRef:
        key: NODERED_CREDENTIAL_SECRET
