apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-postgres
  namespace: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant-postgres
  template:
    metadata:
      labels:
        app: home-assistant-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-01
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: docker.io/library/postgres@sha256:7341002d2b8c7c5bdd7542a671a95b36196c0b5b888daf454ae4fc33ba5346d7
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: home-assistant-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: home-assistant-secrets
                  key: DB_DATABASE_NAME
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-run
              mountPath: /var/run/postgresql
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: home-assistant-postgres-data
        - name: postgres-run
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-postgres
  namespace: home-assistant
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: home-assistant-postgres
