apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: home-assistant-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DB_USERNAME: "homeassistant"
        DB_DATABASE_NAME: "homeassistant"
        DB_PASSWORD: "{{ .db_password }}"
        secrets.yaml: |
          recorder_db_url: "postgresql://homeassistant:{{ .db_password }}@\
            home-assistant-postgres.home-assistant.svc.cluster.local:5432/homeassistant"
          nodered_url: "http://nodered.home-assistant.svc.cluster.local:1880"
          nodered_username: "{{ .nodered_username }}"
          nodered_password: "{{ .nodered_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: HOME_ASSISTANT_DB_PASSWORD
    - secretKey: nodered_username
      remoteRef:
        key: NODERED_ADMIN_USERNAME
    - secretKey: nodered_password
      remoteRef:
        key: NODERED_ADMIN_PASSWORD
