apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    bgp-advertise: "true"
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/bgp-control-plane
  selector:
    app: home-assistant
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: hap
      port: 21063
      targetPort: hap
      protocol: TCP
