apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  volumeName: pvc-bc354a6f-5a1f-4a0e-85fd-13bbb74f666f
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-postgres-nvme
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nvme-homelab-01
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - homelab-01
  hostPath:
    path: /persist/postgres/home-assistant
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-postgres-data
  namespace: home-assistant
spec:
  volumeName: home-assistant-postgres-nvme
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme-homelab-01
  resources:
    requests:
      storage: 10Gi
