apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-cors-config
  namespace: obsidian
data:
  10-couchdb.ini: |
    [couchdb]
    single_node = true

    [cluster]
    n = 1

    [chttpd]
    require_valid_user = true

    [chttpd_auth]
    require_valid_user = true

    [httpd]
    enable_cors = true
    WWW-Authenticate = Basic realm="couchdb"

    [cors]
    origins = *
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
