apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-creds
  namespace: obsidian
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: couchdb-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: admin-password
      remoteRef:
        key: COUCHDB_PASSWORD
