apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apolline
  - darkbit
  - distrojeff
  - pulse
  - ism
  - nixagent
  - rupanism
  - spatia
  - cr-demo
  - soluble-rupan
  - photography
  - majorfinder
