apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - volumes.yaml
  - secrets.yaml
  - db-dump.yaml
  - dumps-to-r2.yaml
  - library-volumes.yaml
  - library-local.yaml
