apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-secrets
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: backup-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: r2-access-key-id
      remoteRef:
        key: R2_ACCESS_KEY_ID
    - secretKey: r2-secret-access-key
      remoteRef:
        key: R2_SECRET_ACCESS_KEY
    - secretKey: restic-password
      remoteRef:
        key: RESTIC_PASSWORD
    - secretKey: db-password
      remoteRef:
        key: IMMICH_DB_PASSWORD
    - secretKey: home-assistant-db-password
      remoteRef:
        key: HOME_ASSISTANT_DB_PASSWORD
