apiVersion: ENC[AES256_GCM,data:zbM=,iv:CbWMt76FbcYmH06lp8u0COcL+ycHPXx/gZc+gUT4KtU=,tag:6AZYbIDLipsxUcmvu6emWw==,type:str]
data:
    token: ENC[AES256_GCM,data:S4d7LEJup/hBlTFn/isun4cdzV+nG6zKJMSVW18qkNHCYJWlpSCjIuOtIXGW33A2Vmh/bxIEc/al22nRvfBywhcs1XZBRjhOnab/yVNyn0USvOlq,iv:pYm7ABu1HE3Y/cmuwOYoIpCywSXwRbhrN4FABiD9ZuY=,tag:7Xh+8dbwolRhY4j91E/EnA==,type:str]
kind: ENC[AES256_GCM,data:L/W33pyN,iv:84G3Lrj9exYmt1C8Gu8s3t3JMe2ozbAf2egjqRklaJc=,tag:s1kv0TUx3Wr/ju8RRuxvEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uynXvZfTQKsYIVQcsG1Q/A==,iv:LxBVjc8t4rGoyTX86uzmdkF7um1TLvmypH0xRecwkNs=,tag:tbIFBJEEcXJPWkRkSoIvJg==,type:str]
    namespace: ENC[AES256_GCM,data:fT8baDBgfp+47/LroeqUdQ==,iv:Av7Z20ryLKwrpa8geqPU3PYznzEKaB1Lx/fT70RR41w=,tag:vFrerCRfT4s8y6mNf8fCtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cThSOS81dTRPZnZBRnI4
            UDU2eDQ4bVhVdmMzT1ZXREJLK09DQ0NBem1VCjFlc2FtWEozWXRPNlBIQW1mZER6
            ZnhXeU1KSlFwRjdQTnlCTHNKT0d2dHMKLS0tIGhyRjBHbFV4dmxyRzI2VmtnNmM5
            TTRlZnVaR0pGT0xVRm5YNHdiMjF1cUkKyJkTqQcLqjWT1hBMuq6OxlTF/yf3CqzV
            WbjUC9RhEvy1iaOzi6ZNHHJTmgQdiEK+Bz0rnQ12o47hpbWh17lq8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-03T18:30:35Z"
    mac: ENC[AES256_GCM,data:LkON29uhj3aFT4JRkm2pBRXguYTbtrmRBOYS4MNpjAz9mHWcvQeHsNsLoyDNbtTu6xXJqw2qhLFyZME2XeUOXzQkp4lKzoLsZd0VmCX9Ig5n5WVBjnG8ISn73r5ZEGlCQujGOv1iq3BUIXB1TOAbnisVCLxbqOWToQP1sEINxj0=,iv:XVj7SbE4R8vic/AmdHkKtz+14X38ZP+oM9RCM9/JMOE=,tag:tet0ZinBJVK6XLqO6h0KNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
