apiVersion: ENC[AES256_GCM,data:jok=,iv:nfGw7RTeZ2g6MR7068/RHS12cbbDfz7z7Ew5tyA8iSw=,tag:uxgLVmCZWykKnhrV9+QatA==,type:str]
data:
    token: ENC[AES256_GCM,data:hOflyTsJdoiNQVsHTppOP4ru9+uv9+sZQmIh4AmbT0A4YRhUs3TxdaoSi1xgzodwbiobVqkM4eQfpP9+KYUwygzoBBn9rdDyqFLos9EZvZaqNdKR,iv:T2+m+31EmvQ+XjtNXATCsNcrpSxHlZXMgCaoZku0M6w=,tag:p/LMbM+fGi33cmaS0ta8Vw==,type:str]
kind: ENC[AES256_GCM,data:bYcY0K5Q,iv:jRzumxxLwdgyITrofjVrGo1gZZKyqknM/OW4rFda4eg=,tag:s33jVXOKOCGuuxIiigyCjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YoLazGkp6TIpngDUNjOLkw==,iv:AXPD/crEPe1jk4BBzaoHMYN9Ad1uW2x9NyePRyo+BAI=,tag:g/9Xph5cKJbkn9zNY45F1A==,type:str]
    namespace: ENC[AES256_GCM,data:rLIqzKyYbnRV4fTPIppSDQ==,iv:Xecj3rGytSa95P+ktETMVtPcypVpPYxvcDeMzLJ4iTs=,tag:WxaJ7o5bOMQ1s8+4pzQKAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV01lRjlCOUhZajhMRWxK
            ZGx1T2lPSUxxdmFYWXNWQVI2R0RrVlBkbjNvCjNrUlFQK3VZaGxLZDMwZjJQaDRU
            cjI5dVptTTg1byszWm1MQVZXelRpT2MKLS0tIGtmckIycUk5MGR6UGxONWlyUHBH
            Rkw3VjJ2bnoyN1hOeEFWRTlHb2p5VzAKQD5L8VOSLGNEUA3AZIBDq6/RWNzBmCNv
            0XDO+iWNwUyENiiXzQecOGrB5eehRqQTGTAPG7WYcvMKjgquflSg1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-03T18:24:27Z"
    mac: ENC[AES256_GCM,data:1ZmL/i4I/VdDUNoamMDK7WZl47xuyFsoGaSOB2yyUjfhGZlMsYtjWGtp4ZZaR3Gi8MGKXtz2kE5owOPaoZIDCfRYmfio3tsyXo0nYNWIrfz46VXBl4sA+cSC8xBh5fQl5wTTqWdls3sxH6OH61dFQNPWh+v7CswXbv37yU98sQk=,iv:nSkF2BOtWbnElKr/4epDZPZErT1Fm/I/Ck5Tfovp+gE=,tag:U+qiZYOixlLsQ6h5i/S1SA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
