apiVersion: ENC[AES256_GCM,data:X44=,iv:YsoT4nZfN1DR+Il3CNmrMMbSXkHg6t4gc0Sc5fzA8HM=,tag:9SHn4xeB8jo6ZECKs2Ar2A==,type:str]
data:
    token: ENC[AES256_GCM,data:kf+ButeqKMqm29FfDmRIQbx58nVaijdu8oh4sQMbalDENWFs1h8KMc+SYGAkLmxMww5VRc7SxKHlDlHoRGAZfVmSHI8rstdqpclJDybxamARPCHa,iv:9a7pQKL4SaFZEaYC3HHhOQAtzeK1f81u0rOStS/oZac=,tag:HO0Zp1pxE29xnmcsVJSPeA==,type:str]
kind: ENC[AES256_GCM,data:BaMPiEoJ,iv:Q3vE93lkzd8XCq1kKLhUY7aL+lZY6dPFVQbsg7EZqrs=,tag:k836ZRQfHdFIy/9sKZD+1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8EGYwfvvJfpKVVshOvg0ag==,iv:QOZJy4Y5L50VuLqO7PqZ+8M6h3Ezj1gXyzr2D3XW/vU=,tag:yT8DL5yby9yjhRoHZAHnBQ==,type:str]
    namespace: ENC[AES256_GCM,data:SuAj+LYgmcq7hoUzp1y98A==,iv:sF3/stIFxlWk9qQ+0MT5Uf6amN2Eo1ljJPat1F4i6Ak=,tag:2LeCXd6onzjHpCUadPewhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bytxOWxXUE95cFdtekl6
            TVYrcVVFQklvdHlFSUh4OFpvUXlGcWg3K3dZCjcxMEhaTGxFcW9QL3M2YWdqQ1lm
            cWZuYTNaUnNFcURBdWdkeEVKaVdKWjAKLS0tICtxZE9vZjZodVJES2JYUDVWYjBy
            enh2cThMZ0RmdktWNVByOTFtUFo0ZmcKhFI0+K/+BeeokwR5j6zyuj6VC9Z6XFOP
            2R0xXqwnAaVrP1aZcR/KAkiGzFfEEB4QPDwmGR1OU8dQzqhHLRWyFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-03T18:34:26Z"
    mac: ENC[AES256_GCM,data:ScDOTtOXN9ZrcgHKDjDF4otVFQt2Yy0GWAwhVP4I+n2NvM6AgeA4jsng/45NSdGwghf5DqvDYKjjxog/4f8c+GvQceP0Ec+hC0l2Uxow6Xld+GJTMDPTFL7TVYOvU9wgzXYtU0+Qh9M5L/h7+0HxepYZpSAyfWHIYW97C9Wfw1I=,iv:R1l6wBdcvUEEGcWSIwR/tOeQYxlzdYG5Bo468wDEiuI=,tag:sUXtL0IqLdY+FFG7jlj0kA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
