apiVersion: ENC[AES256_GCM,data:OU4=,iv:ltLuaysbHlAmB+Qcg4GGeNTGc1dlbnBt0Tx/EH3sBmI=,tag:1sVC+fFaK2yuAgGtiBkDMw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:3d2jI5gNM1r+D35fntrkLt3ElZ1n1XZcaK8tHO6P/W35wtd2wnPnR/8adYUmskBQE23J4wm9g3snNAD2/zzS/nPwWZ2/vlqLq6iTwpHlNXMLFE9phQZykwy0hirK9TyQCb0GdaXnLePZ7Ns5IePu9FK+v96sZsPQykvaOtOQgp/dNq7jzOXpdACMSd0W1WEqxEJXOaZ6PVRNl/MKWkCvaVIgXI5SBT14YDUDPFk9tRmhcmaZ05Aa5MnT7vBw7jpnNFEGoIi90ifdWTLzldpsEFBKbkzJPhaVY4awmQXng8rqZs+n+T3xmlbXLD8=,iv:4flMzc1ePQRiAcOa8qdFEJyjuK7Rs/FygBM2FFIoaA0=,tag:q4XDq7h3w8rA3VkihMBbRQ==,type:str]
kind: ENC[AES256_GCM,data:Y9BEk71e,iv:+sVdGlFrvBTXf4yBr62lWxAzx/ew3txg5rtyX+8W2z0=,tag:rkTpbdCL+8/Q6mXgB+aEjA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rBN4gNjG0p9J,iv:cPT/osRJXAzkk6rC3GzKt5ffLj/v/O93yb7SSkq2Qc0=,tag:ROczsOUS3buXLcDafAlRkg==,type:str]
    namespace: ENC[AES256_GCM,data:jXDVklIPR9Q=,iv:xkSvZ80UN3ghZGfiidWgElhzZ2ATGB4rYgEIq5KG3LA=,tag:j8srIwY63QP/pMmrKp8JZw==,type:str]
type: ENC[AES256_GCM,data:NZaIVmR9G4xVzFqRVYGtHkmOIk7IH8TilHoRl7qC,iv:xQ5KqsY5BlyFQM/S4aJq/+KPTPIC6tjdtEU7P/FzP18=,tag:0Jd6vQKvelRyTfRuo4Ydhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYzRpZnhQSHE3c3ZReWhL
            elV0eHdnL0h6SkY1MUNtRk50cVhVYzlhanlNCkVYZnR4WW8weDUrckUzYVhqdlJx
            SG1PYlRGRVJNUTFRUXUwY0FwVENwOGMKLS0tIDUxbTE5MmJyRjJwR2pPalVEMmpq
            MUtGOERPZFROM3dpQm9ZaHZ5dDBib00K6OkUqgGDXX4H+yxMlF6zFCOUg3aLc7D0
            Q4PDYX3Ki3MO6zSDRkTuWmJ7efgSXPbATEzyVJIK2ImQ7KrpfUzj6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-06T23:54:23Z"
    mac: ENC[AES256_GCM,data:SUq+NDqpW0FE20QIs7x9Bmc6Y9trbOvbc05nP17/+5BzJkMMeMs7DUqGis+XiZZrs6ySNS3v5HIJC5Fpq5ZUSfxUAN6GaRUyoTMLh1tolrYw9QJXG+7z8gosQFj3AiGQrVg1uKzQg0VVmEGxtzreMru4RmPsm7y//ZbDoX29wOI=,iv:HMPAEFY/uPXKzYWSmJY9vvhv9i3KFjQSInM3fqdzspg=,tag:tn5+HwuqLPbPb4B42cMYFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
