apiVersion: ENC[AES256_GCM,data:91I=,iv:LPaFzwFfxorbZgtGfqMKuBSjlET7hR4yL0efCJcUOFA=,tag:n1egnAeQhZCArbAFeRcrSQ==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HsYjIBjSuHqTFlBD1m/xBTi/CvgRgav4SQNUXI5W/u5deSKesuCcFOfyWna63hlfozjngu0A4jcgXcYB3DbwCS+2ZINdUdydDBk3owXe6EB5BGRTeGJCDsi3idaeZ4Inv7CA0n/3BbnUJisJjrYMNdDkclZJ/faTfT3aBUcJeiUDHMYQYKaW9vQaEfQ3Ak8k+XljGKxq0w/+7qdx+NsaJBgVE8c2kI79JeF4dmdoUzui8fexwma2mvEw7jQY69c9upeo59QH2VGV1sde+5jT1mtcjKR1LUrGdYX5D1UJVGJqTAGhXOzbu4X44bU=,iv:8Nqzv7FuamnVAAWIO1mW/el3NYhiJJWhVB8Ei8sY2l0=,tag:3sBHX3/CIX0Eum7xizFfcA==,type:str]
kind: ENC[AES256_GCM,data:KEnTTYXB,iv:yJRG5h508dHD4UbBPy3lMMfN6iTMr5k5W6Gnv+LC4Ks=,tag:Y4PhWFU5owyIylrkeunbTA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7rIPTU1N5Z61,iv:HbIcj8KzKPRPi9t/5Yi8kBBAut0MBKSWtDoygPY5TYY=,tag:nZ2zH9OJ0+gKc3GPfbZkng==,type:str]
    namespace: ENC[AES256_GCM,data:cCwGfPGkknpiI+s=,iv:LNxvggXzf3F3FFUE+lOvYemTODwkn5ixvOx40fnO3oc=,tag:4BNR7yn6JgQC+7Rxz1EsWA==,type:str]
type: ENC[AES256_GCM,data:f9YztH37DUHf7yE3vl72Le3TtS1q5m3wNDqbdLvI,iv:K+3t25YjCvnWomd6ZvMH2V142vYvRw9f0DIauye7E4U=,tag:PUoaVVGUzO8QDrEherTZMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVTRDRFBuaDVjZVJPQ1gz
            aDJYdWNEbzRkcFRYQnFNTlNSc3RqWUFRZEhjClNBN0lwSjNhZFJ1ZHpoOFVHMUpj
            OUdibzVHOW10dEtvNnA0TUhndytUQ0EKLS0tIGNRbndBUVhGc3hPcGJpYnlEMXJm
            Qy9iWVdZRTdEMHBKNFRJalRZcU51R0kKNBAkq3UCEqAIvwvpDzm6cyvkCceB8NS6
            glt+9oy3uyLzJ1Plj7DjJScr15lW5KpprLait2/HFe2E/J34aLd2YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-06T23:35:58Z"
    mac: ENC[AES256_GCM,data:mmUkgfas4fru1lhEZC5m7PGeycbaZcIOz6OletFqh9E9ToLPLOGMOtAD8Gf+OMMtCZiT5DoLLjx89pm7CYwfQoeD1dX6vfjSQ7z9ZHpU5iTbQ914olTPJgKcF3pXOrBHo1GzUNNDiKn4rjTVwBC3SSIqSVbBDtmYl6BbuhIhtjs=,iv:y2nXzoH6Lt5AFd0iWGvVnFh7MpWP9524nLa/3gfeVMA=,tag:5eKZe8HjI4wtAHu560eiRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
