apiVersion: ENC[AES256_GCM,data:7fY=,iv:wP1bWdwBm4ENJDdvjRRiHBoH6A8XVu5ux5pieFVpJc0=,tag:Thyx4GrO48FIjFYrGrHtFw==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:Hn5leKE3BvydGY03eNBqiw0TZe+OdQZahOFtpmdN97A=,iv:QNqi/TEh2SxvUVhV4VuDOK7wYDQG2ezBlUoZx1TGX9E=,tag:/Y112bCS/nU7dATLKLjzTA==,type:str]
    admin-user: ENC[AES256_GCM,data:UfSdvvY9vWc=,iv:PuQYVpf6DnyzuwlH+BSX9ejPCg4yabn2afet7blEdrA=,tag:9ei3FDYgH5NLyXyBeR4wxw==,type:str]
kind: ENC[AES256_GCM,data:586Y+o4R,iv:RLwYM4x1paIxk5CmA27EpY4PR35/GieSPc7ge+CxsD4=,tag:XVoU1Mh2rP7cvWfSVDEd1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HCJM1ZXmS5rzKg1PCbO7l9fErw==,iv:5RGNevcf4Yzzs1gA4FHenBlc7nNGJsXVAekdRl0imnw=,tag:1pMheIWHXEFtfbp2P4a9ig==,type:str]
    namespace: ENC[AES256_GCM,data:/lB997Lcah8OOAVNTA==,iv:xsIKHD//M/9qPjJhC4oQRymxRsUbzxMPlxSois/+6DE=,tag:+eQeQcACqybRSe6B0LseaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTm9qb2ZhblB1V01zb2wr
            cGRIZnhSZ2J4cFJUYkMzb1k2bE05Z3ZRQWprCnE1U2xLN2VDcS9jcmYzdWJiZ1A1
            NXVvMHVxU1pZVWIwNCtqRHBITzZ6OFkKLS0tIFNoc1ZFQWlBUGtOSFlsZ3p6TnBG
            QWxsYndwaEJPUm1GVWREOVVackM0TjgKPMkaW0BYce9OUx5mKhKSoCKZEva5rDkU
            v1tOtc8b3qwBhRK4ipI0ha/+FEHzB683dHpu9cuII3oacPuyvGPO2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-03T21:59:37Z"
    mac: ENC[AES256_GCM,data:3sATUdnQZIWgx3tMdreLyjePijxxR/gsrOwP156KPazg1J/W19HKlFydcqQqL7vMrFHrJJfdURV0iq1FcBhhIP9skYznvsOXktqe0yVi1Hgux/S7oCxTL0nvt5p9CgIkS3JvClXEOfNd8j/8aTD9ixaj2lvhNRkFbFD5FxQLj+w=,iv:Zs/zhhjq/AtBQfpla0NY/mBxl8rkummK0+C2CuacB4A=,tag:UTmd3ZCcPq4VK1f0UhJVWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
