apiVersion: ENC[AES256_GCM,data:H2E=,iv:fneffccf+H9qLAvPZ3zDnUF7tmAF0XGlBnt90rpZVm4=,tag:9g/EGHaFVjqeF7J9zGtNCQ==,type:str]
kind: ENC[AES256_GCM,data:ko/CqGtZ,iv:Jsn5vMo73V3Z/+Hlt0v3CCe2vEiD8sM/zXVyAgIABOk=,tag:GRlIKB7SZJx6kKB7U8imWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gEL9uQNyjhU=,iv:W1mAyKiR+xHmeFIy4eX0BnhwSJBKAmPJQFQaQRYVL3M=,tag:NT5qmRu7FX57PI/HKx5TdQ==,type:str]
    namespace: ENC[AES256_GCM,data:K1HW0xc=,iv:vWShGP5YeMV+NcMr+2xK3xPV6X5ZISbjZEAJ7iAkf5c=,tag:347vZ+TPbOSe1+9vBAIMHA==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:buoiHCJQ/U5JXmz60EnlZF5cbM+6lE2SbTzvAcDB/aH8eIW03YutZPn1zGzpjm/BSZSZouBuC28=,iv:Eu/89SndfJ9fJ9q7R2NcWYRs0NZtO8nxLP1hCCzqwjI=,tag:fQDiEyJAhhln+L1QhVXgBQ==,type:str]
type: ENC[AES256_GCM,data:gu8V9hp5,iv:2+B1TCeVLG2BXdYCK00wUytus63jz3q7xklhJyaX+Ns=,tag:v8Ebc2TpIq/DZfYLhsVUjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSmo4STRiczA5UURpaVl6
            NVZFRU5nVFBOQ3FLeWE3T01DVGtpNVB6bWc4CjVxdVlMZ0w0YlQ4Y1FhUElFVFFn
            NVAvS05za2NHOTg3NkY0a0kvOVhPb28KLS0tIGdWby9QcTYweU8zM1AvLytubnFo
            ZXFaZUVzb0s2bVc5L0o5RTFjTVdkTWcKc60aexp+fpi7aZNEGMZ+GID/VvewtmPw
            3gj15iCq4RuOoZ9THx74UhW287FvKBNH/ijVun5QDA2cN27KrAwrrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-20T06:57:56Z"
    mac: ENC[AES256_GCM,data:U7dqlA6BqkFgfj4HUIDdlKyUptnG/XEK+PNdGpjk0QGc+BhW5pagZC1dxLHA41bIW7m0NxOWWU/Rb9t2wwRswz3YSym0ccE08WyYczygocIUx6qSzby9OtENbhA0KMGDuLAyMzZI/L/yxrUpis/uwH1wlHlwQJEQLOjrXKm10T0=,iv:mW1E36JPgvtfbwsSWoXTyuUKFBsBLlyuIICFY/CyY1U=,tag:IIE69fOJIK6dqovIdy3e7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
