apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - eso-gitlab-token.sops.yaml
  - grafana-admin-creds.sops.yaml
  - ghcr-pull-photography.sops.yaml
  - ghcr-pull-majorfinder.sops.yaml
