---
extends: default

ignore: |
  .git/
  .direnv/
  .worktrees/
  artifacts/
  gitops/clusters/*/flux-system/gotk-*.yaml
  gitops/ingress/crds/gateway-api-*.yaml
  **/*.sops.yaml

rules:
  document-start: disable
  line-length:
    max: 120
