apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-ntfy-data
  namespace: observability
  annotations:
    helm.sh/resource-policy: keep
spec:
  volumeName: pvc-700e8502-6736-427d-8c84-3b53c766fbe5
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 1Gi
