apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse-web
  template:
    metadata:
      labels:
        app: pulse-web
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: ghcr.io/jeff7712/pulse-site:0.0.89
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
      volumes:
        - name: tmp
          emptyDir: {}
