apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/external-secrets/external-secrets
            newName: registry.rupan.dev/upstream/ghcr.io/external-secrets/external-secrets  # yamllint disable-line rule:line-length
            digest: sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1
