apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: alloy
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  postRenderers:
    - kustomize:
        images:
          - name: docker.io/grafana/alloy
            newName: registry.rupan.dev/upstream/docker.io/grafana/alloy  # yamllint disable-line rule:line-length
            digest: sha256:51aeb9d829239345070619dad3edd6873186f913c84f45b365b74574fcb38ec0
          - name: quay.io/prometheus-operator/prometheus-config-reloader
            newName: registry.rupan.dev/upstream/quay.io/prometheus-operator/prometheus-config-reloader  # yamllint disable-line rule:line-length
            digest: sha256:7d9e4eea5f1139e602508871f422b0116c60e87c662f3dcd234d5ab60cd0d8c1
  values:
    controller:
      type: daemonset
    alloy:
      mounts:
        varlog: true
        dockercontainers: true
      configMap:
        content: |
          logging {
            level = "info"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.local.receiver]
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.journal "journal" {
            forward_to = [loki.write.local.receiver]
            labels = { component = "system-journal" }
          }

          loki.write "local" {
            endpoint {
              url = "http://loki.observability.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
