apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-canary
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gitlab-project
  target:
    name: eso-canary
    creationPolicy: Owner
  data:
    - secretKey: canary
      remoteRef:
        key: FLUX_ESO_CANARY
