apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gitlab-project
  namespace: external-secrets
spec:
  provider:
    gitlab:
      url: https://gitlab.com
      projectID: "85910419"
      auth:
        SecretRef:
          accessToken:
            name: eso-gitlab-token
            key: token
