apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-project
spec:
  provider:
    gitlab:
      url: https://gitlab.com
      projectID: "85910419"
      auth:
        SecretRef:
          accessToken:
            name: eso-gitlab-token
            key: token
            namespace: external-secrets
