apiVersion: v1
kind: ConfigMap
metadata:
  name: lidarr-extended-config
  namespace: media
data:
  extended.conf: |
    [General]
    enableAutoConfig = false
    enableAudioConfig = false
    enableVideoConfig = false
    enableUnmappedFilesCleaner = false
    enableQueueCleaner = false
    enableChangeCategory = false
    [DownloadClients]
    dlClientSource = "deezer"
    [Audio]
    audioFormat = "native"
    audioBitrate = "lossless"
    enableBeetsTagging = false
    [Connection]
    lidarrUrl = "http://127.0.0.1:8686"
    autoUpdate = false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beets-config
  namespace: media
data:
  config.yaml: |
    directory: /data/music
    library: /data/.beets/library.db
    plugins: fetchart embedart scrub
    import:
      move: false
      copy: false
      write: true
      incremental: true
      quiet: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calibre-web-dirs
  namespace: media
data:
  dirs.json: |
    {"ingest_folder": "/cwa-book-ingest", "library_folder": "/calibre-library"}
