apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-vpn
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: media-vpn
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: MEDIA_VPN_WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: MEDIA_VPN_WIREGUARD_PRESHARED_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: MEDIA_VPN_WIREGUARD_ADDRESSES
    - secretKey: VPN_PORT_FORWARDING
      remoteRef:
        key: MEDIA_VPN_PORT_FORWARDING
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-app
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: media-app
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: SLSKD_USERNAME
      remoteRef:
        key: SLSKD_USERNAME
    - secretKey: SLSKD_PASSWORD
      remoteRef:
        key: SLSKD_PASSWORD
    - secretKey: SLSKD_YML
      remoteRef:
        key: SLSKD_YML
    - secretKey: DEEZER_ARL
      remoteRef:
        key: LIDARR_DEEZER_ARL
