apiVersion: v1
kind: Service
metadata:
  name: rupanism-svc
  namespace: rupanism
spec:
  selector:
    app: rupanism-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
