apiVersion: v1
kind: Service
metadata:
  name: spatia-svc
  namespace: spatia
spec:
  selector:
    app: spatia-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
