apiVersion: v1
kind: Service
metadata:
  name: soluble-rupan-svc
  namespace: soluble-rupan
spec:
  selector:
    app: soluble-rupan-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
