apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/automation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: eso
    - name: observability
    - name: obsidian
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: renovate-dashboard
      namespace: automation
    - apiVersion: apps/v1
      kind: Deployment
      name: renovate-approval-webhook
      namespace: automation
