apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: websites
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/websites
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: apolline
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: darkbit
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: distrojeff
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: pulse
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: ism
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: nixagent
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: rupanism
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: spatia
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: cr-demo
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: soluble-rupan
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: photography
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: majorfinder
    - apiVersion: apps/v1
      kind: Deployment
      name: website-deploy
      namespace: rupan-dev
