apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: photography
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photography-web
  template:
    metadata:
      labels:
        app: photography-web
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: ghcr.io/jeff7712/photography@sha256:731128663e8bb12861fcf2b801bd0a671478607c44198bf5166812dfc88d57e6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
      volumes:
        - name: tmp
          emptyDir: {}
