apiVersion: v1
kind: Service
metadata:
  name: cr-demo-svc
  namespace: cr-demo
spec:
  selector:
    app: cr-demo-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
