apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: renovate-github
      namespace: automation
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: ghcr.io/renovatebot/renovate
              newName: registry.rupan.dev/upstream/ghcr.io/renovatebot/renovate
              digest: sha256:97006d85961032ad4a991d70c1a8b8255038f4cd17c8bae732a263f735261130
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: renovate-gitlab
      namespace: automation
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: ghcr.io/renovatebot/renovate
              newName: registry.rupan.dev/upstream/ghcr.io/renovatebot/renovate
              digest: sha256:97006d85961032ad4a991d70c1a8b8255038f4cd17c8bae732a263f735261130
