apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: alloy
      namespace: observability
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: docker.io/grafana/alloy
              newName: registry.rupan.dev/upstream/docker.io/grafana/alloy
              digest: sha256:51aeb9d829239345070619dad3edd6873186f913c84f45b365b74574fcb38ec0
            - name: quay.io/prometheus-operator/prometheus-config-reloader
              newName: registry.rupan.dev/upstream/quay.io/prometheus-operator/prometheus-config-reloader
              digest: sha256:7d9e4eea5f1139e602508871f422b0116c60e87c662f3dcd234d5ab60cd0d8c1
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: quay.io/jetstack/cert-manager-acmesolver
              newName: registry.rupan.dev/upstream/quay.io/jetstack/cert-manager-acmesolver
              digest: sha256:dbc7cc1354f603918e7c5af7f55a0a620537394452c93a565bde75c6f48e8837
            - name: quay.io/jetstack/cert-manager-cainjector
              newName: registry.rupan.dev/upstream/quay.io/jetstack/cert-manager-cainjector
              digest: sha256:ccf6b919ec0500745a47a910118f834f9636d0aac1ff221245cd2557ed8c7c98
            - name: quay.io/jetstack/cert-manager-controller
              newName: registry.rupan.dev/upstream/quay.io/jetstack/cert-manager-controller
              digest: sha256:416a2d76870d996460e62bd7f521bf14fa017be9e3e904aab92163a331fcb61a
            - name: quay.io/jetstack/cert-manager-startupapicheck
              newName: registry.rupan.dev/upstream/quay.io/jetstack/cert-manager-startupapicheck
              digest: sha256:d8ab6416e6e7303a86fa0a8daa82c94a8001f21c9d78eb2e7db20534e5d07ae8
            - name: quay.io/jetstack/cert-manager-webhook
              newName: registry.rupan.dev/upstream/quay.io/jetstack/cert-manager-webhook
              digest: sha256:d8b3961b51c8c7320633f8208dc46bf88aa13804d0f7cbe48a096b2c523cee42
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: ghcr.io/external-secrets/external-secrets
              newName: registry.rupan.dev/upstream/ghcr.io/external-secrets/external-secrets
              digest: sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: docker.io/grafana/grafana
              newName: registry.rupan.dev/upstream/docker.io/grafana/grafana
              digest: sha256:2d1f9ae67c1778d33e291d4c3c759cd8b650e67491f02533499eb950e075eeb5
            - name: ghcr.io/jkroepke/kube-webhook-certgen
              newName: registry.rupan.dev/upstream/ghcr.io/jkroepke/kube-webhook-certgen
              digest: sha256:8ce13c365c8e9ced0aad5ef350a53c50b7ca5817f99d856b9eec895db1056728
            - name: quay.io/kiwigrid/k8s-sidecar
              newName: registry.rupan.dev/upstream/quay.io/kiwigrid/k8s-sidecar
              digest: sha256:694950d736c8b532eba4006527ccbdac98fefc9f30b3346ba2de50b6cad91c94
            - name: quay.io/prometheus-operator/prometheus-config-reloader
              newName: registry.rupan.dev/upstream/quay.io/prometheus-operator/prometheus-config-reloader
              digest: sha256:7d9e4eea5f1139e602508871f422b0116c60e87c662f3dcd234d5ab60cd0d8c1
            - name: quay.io/prometheus-operator/prometheus-operator
              newName: registry.rupan.dev/upstream/quay.io/prometheus-operator/prometheus-operator
              digest: sha256:9e53e13139218aca79ee000172de73355e9174ef2904585bfad9497fc71aae2d
            - name: quay.io/prometheus/alertmanager
              newName: registry.rupan.dev/upstream/quay.io/prometheus/alertmanager
              digest: sha256:51a825c2a40acc3e338fdd00d622e01ec090f72be2b3ea46be0839cd47a4d286
            - name: quay.io/prometheus/node-exporter
              newName: registry.rupan.dev/upstream/quay.io/prometheus/node-exporter
              digest: sha256:6112664fd761bb964d8a2d3d0119d6c8402618a89edbb3a43c8f7b4090fb53c9
            - name: quay.io/prometheus/prometheus
              newName: registry.rupan.dev/upstream/quay.io/prometheus/prometheus
              digest: sha256:f39df5334dee301b885f77e0ff1159f5d8a43bf9db518f885544594799a1e3c2
            - name: registry.k8s.io/kube-state-metrics/kube-state-metrics
              newName: registry.rupan.dev/upstream/registry.k8s.io/kube-state-metrics/kube-state-metrics
              digest: sha256:6b2f0b6f2f86ac5b1aa883a033a8dd55bb96c16d191ec973393bdaadaddac914
      - op: add
        path: /spec/values/prometheus/prometheusSpec/image
        value:
          registry: registry.rupan.dev
          repository: upstream/quay.io/prometheus/prometheus
          tag: v3.12.0-distroless
          sha: sha256:f39df5334dee301b885f77e0ff1159f5d8a43bf9db518f885544594799a1e3c2
      - op: add
        path: /spec/values/alertmanager/alertmanagerSpec/image
        value:
          registry: registry.rupan.dev
          repository: upstream/quay.io/prometheus/alertmanager
          tag: v0.32.1
          sha: sha256:51a825c2a40acc3e338fdd00d622e01ec090f72be2b3ea46be0839cd47a4d286
      - op: add
        path: /spec/values/prometheusOperator
        value:
          prometheusConfigReloader:
            image:
              registry: registry.rupan.dev
              repository: upstream/quay.io/prometheus-operator/prometheus-config-reloader
              tag: v0.91.0
              sha: sha256:7d9e4eea5f1139e602508871f422b0116c60e87c662f3dcd234d5ab60cd0d8c1
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: loki
      namespace: observability
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: docker.io/grafana/loki
              newName: registry.rupan.dev/upstream/docker.io/grafana/loki
              digest: sha256:3c8fd3570dd9219951a60d3f919c7f31923d10baee578b77bc26c4a0b32d092d
            - name: docker.io/grafana/loki-canary
              newName: registry.rupan.dev/upstream/docker.io/grafana/loki-canary
              digest: sha256:0dac7d5cb383adb8d3723676a70ed0c65b582e636846f4ce48703556dd509ad1
            - name: docker.io/grafana/loki-helm-test
              newName: registry.rupan.dev/upstream/docker.io/grafana/loki-helm-test
              digest: sha256:2ed6447bbdbcd23019c3fdb02bce6db3fbef296d5a8f77a68d3dbc386bfa43fb
            - name: docker.io/kiwigrid/k8s-sidecar
              newName: registry.rupan.dev/upstream/docker.io/kiwigrid/k8s-sidecar
              digest: sha256:a6b3f707f883108376514489a94d6629109a327b2978e1d826cd104c4ca436df
            - name: docker.io/nginxinc/nginx-unprivileged
              newName: registry.rupan.dev/upstream/docker.io/nginxinc/nginx-unprivileged
              digest: sha256:0c79d56aee561a1d81c63f00eee5fb5fe29279560cdc55e91425133104c7fbe6
            - name: memcached
              newName: registry.rupan.dev/upstream/docker.io/library/memcached
              digest: sha256:c8503d4491edd3110cc07d0465089d3a41cf1daf8645e71149e39a51835e92cd
            - name: prom/memcached-exporter
              newName: registry.rupan.dev/upstream/docker.io/prom/memcached-exporter
              digest: sha256:b6763ecb3c47f2408e0398518851b7f8c5fc46232b2649f8c78a321130c54266
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: nfs-subdir-external-provisioner
      namespace: storage
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
              newName: registry.rupan.dev/upstream/registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
              digest: sha256:63d5e04551ec8b5aae83b6f35938ca5ddc50a88d85492d9731810c31591fa4c9
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: ntfy
      namespace: observability
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: docker.io/binwiederhier/ntfy
              newName: registry.rupan.dev/upstream/docker.io/binwiederhier/ntfy
              digest: sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: renovate-github
      namespace: automation
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: ghcr.io/renovatebot/renovate
              newName: registry.rupan.dev/upstream/ghcr.io/renovatebot/renovate
              digest: sha256:97006d85961032ad4a991d70c1a8b8255038f4cd17c8bae732a263f735261130
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: renovate-gitlab
      namespace: automation
    patch: |-
      - op: add
        path: /spec/postRenderers
        value:
        - kustomize:
            images:
            - name: ghcr.io/renovatebot/renovate
              newName: registry.rupan.dev/upstream/ghcr.io/renovatebot/renovate
              digest: sha256:97006d85961032ad4a991d70c1a8b8255038f4cd17c8bae732a263f735261130
