apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
    patch: |-
      - op: add
        path: /spec/values/prometheus/prometheusSpec/additionalScrapeConfigs
        value:
          - job_name: nas-01-node
            static_configs:
              - targets:
                  - 10.0.30.20:9100
                labels:
                  host: nas-01
