apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voice
resources:
  - namespace.yaml
  - ollama.yaml
  - whisper.yaml
  - piper.yaml
  - satellite.yaml
  - exporter.yaml
  - voice-id.yaml
