apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-piper
  namespace: voice
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wyoming-piper
  template:
    metadata:
      labels:
        app: wyoming-piper
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-04
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: piper
          # Pinned upstream tag: 2.5.2
          image: docker.io/rhasspy/wyoming-piper@sha256:7d39aafac409c2b6b09d999ed04d84c311d632e558b35baa60fad6aac722af7a  # yamllint disable-line rule:line-length
          args:
            - "--voice"
            - "en_GB-alan-medium"
            - "--data-dir"
            - "/data"
            - "--download-dir"
            - "/data"
          ports:
            - containerPort: 10200
              name: wyoming
          startupProbe:
            tcpSocket:
              port: wyoming
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: wyoming
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: wyoming
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /persist/voice-models/piper
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: wyoming-tts-piper
  namespace: voice
spec:
  selector:
    app: wyoming-piper
  ports:
    - name: wyoming
      port: 10200
      targetPort: 10200
