apiVersion: v1
kind: Service
metadata:
  name: apolline-svc
  namespace: apolline
spec:
  selector:
    app: apolline-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
