default_config:
homeassistant:
  external_url: https://ha.rupan.dev
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit:
  - name: Homelab Bridge
    port: 21063
    advertise_ip: 10.0.40.13
    filter:
      include_domains:
        - light
      include_entities:
        - switch.0xffffb40e0608c96f
        - switch.0xffffb40e0608d02e
        - switch.0xffffb40e0608f37a
        - switch.0xffffb40e0608faec
        - climate.living_room_ac_living_room_ac_thermostat
      exclude_entities:
        - light.a1_03900d642327265_chamber_light
recorder:
  db_url: !secret recorder_db_url
rest:
  - resource: https://version.home-assistant.io/stable.json
    scan_interval: 21600
    sensor:
      - name: HA latest version
        value_template: "{{ value_json.homeassistant.default }}"
