default_config:
homeassistant:
  external_url: https://ha.rupan.dev
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.30.0/24
    - 10.0.40.0/24
    - 10.43.0.0/16
    - 127.0.0.1
    - 172.16.0.0/12
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.217.32.0/21
    - 199.27.128.0/21
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 172.64.0.0/13
    - 131.0.72.0/22
    - 2400:cb00::/32
    - 2606:4700::/32
    - 2803:f800::/32
    - 2405:b500::/32
    - 2405:8100::/32
    - 2a06:98c0::/29
    - 2c0f:f248::/32
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit:
  - name: Homelab Bridge
    port: 21063
    advertise_ip: 10.0.40.13
    filter:
      include_domains:
        - light
      include_entities:
        - switch.0xffffb40e0608c96f
        - switch.0xffffb40e0608d02e
        - switch.0xffffb40e0608f37a
        - switch.0xffffb40e0608faec
      exclude_entities:
        - light.a1_03900d642327265_chamber_light
nodered:
  http_link:
    url: !secret nodered_url
    username: !secret nodered_username
    password: !secret nodered_password
    ssl: false
    verify_ssl: false
    compatibility_mode: false
recorder:
  db_url: !secret recorder_db_url
rest:
  - resource: https://version.home-assistant.io/stable.json
    scan_interval: 21600
    sensor:
      - name: HA latest version
        value_template: "{{ value_json.homeassistant.default }}"
