apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-gitlab
  namespace: automation
spec:
  interval: 1h
  chart:
    spec:
      chart: renovate
      version: 46.284.1
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/renovatebot/renovate
            newName: registry.rupan.dev/upstream/ghcr.io/renovatebot/renovate  # yamllint disable-line rule:line-length
            digest: sha256:97006d85961032ad4a991d70c1a8b8255038f4cd17c8bae732a263f735261130
  values:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    renovate:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      config: |
        {
          "platform": "gitlab",
          "endpoint": "https://gitlab.com/api/v4",
          "autodiscover": true,
          "autodiscoverFilter": [
            "jeff7712/homelab-new",
            "JEFF7712/homelab-new"
          ],
          "onboarding": false,
          "requireConfig": "optional"
        }
    cronjob:
      schedule: "0 * * * *"
      concurrencyPolicy: Forbid
    envList:
      - name: LOG_LEVEL
        value: info
      - name: RENOVATE_TOKEN
        valueFrom:
          secretKeyRef:
            name: renovate-secrets
            key: gitlab-token
      - name: GITHUB_COM_TOKEN
        valueFrom:
          secretKeyRef:
            name: renovate-secrets
            key: github-token
