apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-project
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: gitlab-token
      remoteRef:
        key: RENOVATE_TOKEN
    - secretKey: github-token
      remoteRef:
        key: GITHUB_TOKEN
