apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: automation-secrets
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: automation-secrets
    creationPolicy: Owner
  data:
    - secretKey: ntfy-token
      remoteRef:
        key: NTFY_TOKEN
    - secretKey: dockerhub-username
      remoteRef:
        key: DOCKERHUB_USERNAME
    - secretKey: dockerhub-token
      remoteRef:
        key: DOCKERHUB_TOKEN
    - secretKey: github-token
      remoteRef:
        key: GITHUB_TOKEN
    - secretKey: openai-api-key
      remoteRef:
        key: OPENAI_API_KEY
    - secretKey: gitlab-token
      remoteRef:
        key: RENOVATE_TOKEN
