---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-health-state
  namespace: automation
data:
  cloudflare-tunnel: ok
  longhorn-backups: ok
  longhorn-snapshots: ok
  initialized: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-sentinel-state
  namespace: automation
data:
  initialized: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-image-state
  namespace: automation
data:
  initialized: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-agent-state
  namespace: automation
data:
  initialized: 'true'
