apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-nvme
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nvme-homelab-01
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - homelab-01
  hostPath:
    path: /persist/postgres/immich
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme-homelab-01
  resources:
    requests:
      storage: 20Gi
