apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: immich-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DB_USERNAME: "immich"
        DB_DATABASE_NAME: "immich"
        DB_PASSWORD: "{{ .db_password }}"
        JWT_SECRET: "{{ .jwt_secret }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: IMMICH_DB_PASSWORD
    - secretKey: jwt_secret
      remoteRef:
        key: IMMICH_JWT_SECRET
