apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 5Gi
