apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-project
  target:
    name: cloudflare-tunnel
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: CF_TUNNEL_TOKEN
