apiVersion: v1
kind: Service
metadata:
  name: rupan-dev-svc
  namespace: rupan-dev
spec:
  selector:
    app: rupan-dev-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
